#!/bin/bash

echo "Content-type:\ttext"
echo

</dev/tcp/tjzimmerman.com/2000 && printf "Apache:\t\tUp\n" || printf "Apache:\t\tDown\n"
</dev/tcp/tjzimmerman.com/8112 && printf "Deluge:\t\tUp\n" || printf "Deluge:\t\tDown\n"
</dev/tcp/hyperion.sol.milkyway/443 && printf "Chef:\t\tUp\n" || printf "Chef:\t\tDown\n"
</dev/tcp/jupiter.sol.milkyway/631 && printf "CUPS:\t\tUp\n" || printf "CUPS:\t\tDown\n"
</dev/tcp/tjzimmerman.com/8442 && printf "LibreNMS:\t\tUp\n" || printf "LibreNMS:\t\tDown\n"
</dev/tcp/tjzimmerman.com/2000 && printf "Kloudspeaker:\t\tUp\n" || printf "Kloudspeaker:\t\tDown\n"
</dev/tcp/tjzimmerman.com/25565 && printf "Minecraft:\t\tUp\n" || printf "Minecraft:\t\tDown\n"
</dev/tcp/tjzimmerman.com/2000 && printf "Nextcloud:\t\tUp\n" || printf "Nextcloud:\t\tDown\n"
</dev/tcp/tjzimmerman.com/943 && printf "OpenVPN:\t\tUp\n" || printf "OpenVPN:\t\tDown\n"
</dev/tcp/luna.sol.milkyway/80 && printf "Pi-Hole:\t\tUp\n" || printf "Pi-Hole:\t\tDown\n"
</dev/tcp/tjzimmerman.com/32400 && printf "Plex:\t\tUp\n" || printf "Plex:\t\tDown\n"
</dev/tcp/janus.sol.milkyway/8181 && printf "PlexPy:\t\tUp\n" || printf "PlexPy:\t\tDown\n"
</dev/tcp/io.sol.milkyway/8080 && printf "PRTG:\t\tUp\n" || printf "PRTG:\t\tDown\n"
</dev/tcp/deimos.sol.milkyway/8080 && printf "RancherOS:\t\tUp\n" || printf "RancherOS:\t\tDown\n"
</dev/tcp/phobos.sol.milkyway/3000 && printf "Rocket.Chat:\t\tUp\n" || printf "Rocket.Chat:\t\tDown\n"
</dev/tcp/ymir.sol.milkyway/8441 && printf "SexiGraf:\t\tUp\n" || printf "SexiGraf:\t\tDown\n"
</dev/tcp/janus.sol.milkyway/8081 && printf "SickRage:\t\tUp\n" || printf "SickRage:\t\tDown\n"
</dev/tcp/jupiter.sol.milkyway/9510 && printf "Unified Remote:\t\tUp\n" || printf "Unified Remote:\t\tDown\n"
</dev/tcp/tjzimmerman.com/8444 && printf "vRealize Operations Manager:\tUp\n" || printf "vRealize Operations Manager:\t\tDown\n"
</dev/tcp/pluto.sol.milkyway/443 && printf "vSphere Flash:\t\tUp\n" || printf "vSphere Flash:\t\tDown\n"
</dev/tcp/ceres.sol.milkyway/443 && printf "vSphere HTML5:\t\tUp\n" || printf "vSphere HTML5:\t\tDown\n"
</dev/tcp/tjzimmerman.com/8440 && printf "Wordpress:\t\tUp\n" || printf "Wordpress:\t\tDown\n"
