#!/bin/bash

echo "Content-type:\ttext"
echo

</dev/tcp/184.75.155.33/2000 && printf "Apache:\t\tUp\n" || printf "Apache:\t\tDown\n"
</dev/tcp/hyperion.sol.milkyway/443 && printf "Chef:\t\tUp\n" || printf "Chef:\t\tDown\n"
</dev/tcp/jupiter.sol.milkyway/631 && printf "CUPS:\t\tUp\n" || printf "CUPS:\t\tDown\n"
</dev/tcp/184.75.155.33/8112 && printf "Deluge:\t\tUp\n" || printf "Deluge:\t\tDown\n"
</dev/tcp/saturn.sol.milkyway/443 && printf "ESXi:\t\tUp\n" || printf "ESXi:\t\tDown\n"
</dev/tcp/184.75.155.33/8442 && printf "LibreNMS:\t\tUp\n" || printf "LibreNMS:\t\tDown\n"
</dev/tcp/184.75.155.33/2000 && printf "Kloudspeaker:\t\tUp\n" || printf "Kloudspeaker:\t\tDown\n"
</dev/tcp/184.75.155.33/25565 && printf "Minecraft:\t\tUp\n" || printf "Minecraft:\t\tDown\n"
</dev/tcp/184.75.155.33/2000 && printf "Nextcloud:\t\tUp\n" || printf "Nextcloud:\t\tDown\n"
</dev/tcp/184.75.155.33/943 && printf "OpenVPN:\t\tUp\n" || printf "OpenVPN:\t\tDown\n"
</dev/tcp/sol.sol.milkyway/80 && printf "OpenWRT:\t\tUp\n" || printf "OpenWRT:\t\tDown\n"
</dev/tcp/luna.sol.milkyway/80 && printf "Pi-Hole:\t\tUp\n" || printf "Pi-Hole:\t\tDown\n"
</dev/tcp/184.75.155.33/32400 && printf "Plex:\t\tUp\n" || printf "Plex:\t\tDown\n"
</dev/tcp/janus.sol.milkyway/8181 && printf "PlexPy:\t\tUp\n" || printf "PlexPy:\t\tDown\n"
</dev/tcp/io.sol.milkyway/8080 && printf "PRTG:\t\tUp\n" || printf "PRTG:\t\tDown\n"
</dev/tcp/triton.sol.milkyway/8080 && printf "Rancher:\t\tUp\n" || printf "RancherOS:\t\tDown\n"
</dev/tcp/janus.sol.milkyway/8081 && printf "SickRage:\t\tUp\n" || printf "SickRage:\t\tDown\n"
</dev/tcp/io.sol.milkyway/443 && printf "Thycotic Secret Server:\tUp\n" || printf "Thycotic Secret Server:\t\tDown\n"
</dev/tcp/jupiter.sol.milkyway/9510 && printf "Unified Remote:\t\tUp\n" || printf "Unified Remote:\t\tDown\n"
</dev/tcp/pluto.sol.milkyway/443 && printf "VMware VCSA:\t\tUp\n" || printf "vSphere Flash:\t\tDown\n"
</dev/tcp/184.75.155.33/8444 && printf "VMware vROps:\t\tUp\n" || printf "vRealize Operations Manager:\t\tDown\n"
